spring:
  application:
    name: core
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    user:
      name: admin
      password: admin

jwt:
  secret: a8B3G9f2Hk9J5kL7sD3E8gU1pQ2W7zY6tP3R8wU4nF0V7tQ9eS1L
  expiration-ms: 3600000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Logging configuration
logging:
  level:
    root: INFO
    com.ogame.core.api: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
